version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: lab_nginx
    ports:
      - "8080:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: lab_postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: lab_pass_ChangeMe
      POSTGRES_DB: labdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
