version: "3.8"
services:
  web:
    image: nginx:alpine
    container_name: lab_nginx
    ports:
      - "8080:80"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: lab_postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: changeinenv
      POSTGRES_DB: labu_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
